services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    container_name: api
    env_file:
      - .env
    ports:
      - "4000:4000"
    networks:
      - bridge-network

networks:
  bridge-network:
    external: true
